-- debug
DEBUG_ENABLE = false
-- windows
WIN_WIDTH = 1200
WIN_HEIGHT = 768
-- game
GAME_TITLE = "Disc Room Escape"
GAME_SCALE = 3
GAME_SPRITE_SIZE = 16
GAME_LEVEL_START = 1
GAME_LEVEL_MAX = 5
--
HERO_MAX_SPEED = 220
HERO_ACCELERATION = 3
HERO_DECELERATION = 4
HERO_GRAVITY = 35
HERO_JUMP_SPEED = -7
HERO_JUMP_FORGIVENESS = 0.3
HERO_MAX_VELOCITY = 12
--
SOUND_JUMP = 'assets/DISC ROOM SFX 101/FEETS/DR SFX FEET5.wav'
SOUND_DEATH = 'assets/DISC ROOM SFX 101/DEATH GORE SFX/DR SFX DEATH GOREnew1.wav'
SOUND_DOOR = 'assets/DISC ROOM SFX 101/DOORS/DR SFX DOOR OPEN ROBO1.wav'
SOUND_DISC = 'assets/DISC ROOM SFX 101/BOUNCE MISC/DR SFX DiscBounce1.wav'
SOUND_ALERT = 'assets/DISC ROOM SFX 101/SPAWN MISC/DR SFX DiscSpawn2.wav'