-- debug
DEBUG_ENABLE = true
-- windows
WIN_WIDTH = 1200
WIN_HEIGHT = 864
-- game
GAME_TITLE = "Disc Room Escape"
GAME_SCALE = 3
GAME_SPRITE_SIZE = 16
--
HERO_MAX_SPEED = 220
HERO_ACCELERATION = 3
HERO_DECELERATION = 4
HERO_GRAVITY = 40
HERO_JUMP_SPEED = -7
HERO_JUMP_FORGIVENESS = 0.3
HERO_MAX_VELOCITY = 12